"""create users table

Revision ID: 29b3f80272af
Revises: 
Create Date: 2026-03-29 01:32:34.278008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b3f80272af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_norm', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=12), nullable=True),
    sa.Column('role', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('auth_provider', sa.String(length=20), server_default='local', nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdraw_reason', sa.String(length=30), nullable=True),
    sa.Column('withdraw_reason_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_norm'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_status', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
