"""create all tables

Revision ID: dc0fe7d19e90
Revises: 29b3f80272af
Create Date: 2026-04-05 20:35:33.732003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0fe7d19e90'
down_revision: Union[str, Sequence[str], None] = '29b3f80272af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_verify_email', 'email_verification_sessions', ['email', 'verified'], unique=False)
    op.create_table('guest_actors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guest_actor_id', sa.String(length=64), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_actor_id')
    )
    op.create_index('idx_guest_actor_ttl', 'guest_actors', ['last_accessed_at'], unique=False)
    op.create_table('temp_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('temp_image_id', sa.String(length=64), nullable=False),
    sa.Column('uploader_id', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('temp_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temp_image_id')
    )
    op.create_index('idx_temp_image_cleanup', 'temp_images', ['expires_at'], unique=False)
    op.create_index('idx_temp_image_uploader', 'temp_images', ['uploader_id', 'created_at'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uniq_provider_sub')
    )
    op.create_index('idx_auth_identity_user', 'auth_identities', ['user_id'], unique=False)
    op.create_table('local_credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lounges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lounge_creator', 'lounges', ['creator_id'], unique=False)
    op.create_index('idx_lounge_name_lower', 'lounges', [sa.literal_column("lower('name')")], unique=True)
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_notification_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reply_notification_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('best_post_notification_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_id', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_user_list', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notification_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('idx_refresh_token_user', 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.create_table('user_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('blocker_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_user_id', sa.BigInteger(), nullable=True),
    sa.Column('blocked_guest_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(blocked_user_id IS NOT NULL AND blocked_guest_id IS NULL) OR (blocked_user_id IS NULL AND blocked_guest_id IS NOT NULL)', name='chk_target_one_only'),
    sa.CheckConstraint('blocker_id IS DISTINCT FROM blocked_user_id', name='chk_no_self_block'),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_blocks_list', 'user_blocks', ['blocker_id', 'active'], unique=False)
    op.create_index('uniq_active_block_guest', 'user_blocks', ['blocker_id', 'blocked_guest_id'], unique=True, postgresql_where='active = true AND blocked_guest_id IS NOT NULL')
    op.create_index('uniq_active_block_user', 'user_blocks', ['blocker_id', 'blocked_user_id'], unique=True, postgresql_where='active = true AND blocked_user_id IS NOT NULL')
    op.create_table('lounge_views',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lounge_id', sa.BigInteger(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lounge_id'], ['lounges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lounge_id', name='uniq_user_lounge')
    )
    op.create_index('idx_lounge_views_recent', 'lounge_views', ['user_id', 'viewed_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lounge_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('guest_actor_id', sa.String(length=64), nullable=True),
    sa.Column('guest_nickname', sa.String(length=12), nullable=True),
    sa.Column('guest_password_hash', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_plain', sa.Text(), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dislike_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(author_id IS NOT NULL AND guest_actor_id IS NULL) OR (author_id IS NULL AND guest_actor_id IS NOT NULL)', name='chk_post_author'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lounge_id'], ['lounges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_author', 'posts', ['author_id'], unique=False, postgresql_where='author_id IS NOT NULL')
    op.create_index('idx_post_lounge_created', 'posts', ['lounge_id', 'created_at'], unique=False)
    op.create_table('best_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index('idx_best_posts_promoted', 'best_posts', ['promoted_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('guest_actor_id', sa.String(length=64), nullable=True),
    sa.Column('guest_nickname', sa.String(length=12), nullable=True),
    sa.Column('guest_password_hash', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_by', sa.String(length=20), nullable=True),
    sa.CheckConstraint('(author_id IS NOT NULL AND guest_actor_id IS NULL) OR (author_id IS NULL AND guest_actor_id IS NOT NULL)', name='chk_comment_author'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_parent', 'comments', ['parent_comment_id'], unique=False, postgresql_where='parent_comment_id IS NOT NULL')
    op.create_index('idx_comment_post', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_table('post_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_image_post', 'post_images', ['post_id'], unique=False)
    op.create_table('post_reactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('like', 'dislike')", name='chk_reaction_type'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'actor_id', name='uniq_post_actor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_reactions')
    op.drop_index('idx_post_image_post', table_name='post_images')
    op.drop_table('post_images')
    op.drop_index('idx_comment_post', table_name='comments')
    op.drop_index('idx_comment_parent', table_name='comments', postgresql_where='parent_comment_id IS NOT NULL')
    op.drop_table('comments')
    op.drop_index('idx_best_posts_promoted', table_name='best_posts')
    op.drop_table('best_posts')
    op.drop_index('idx_post_lounge_created', table_name='posts')
    op.drop_index('idx_post_author', table_name='posts', postgresql_where='author_id IS NOT NULL')
    op.drop_table('posts')
    op.drop_index('idx_lounge_views_recent', table_name='lounge_views')
    op.drop_table('lounge_views')
    op.drop_index('uniq_active_block_user', table_name='user_blocks', postgresql_where='active = true AND blocked_user_id IS NOT NULL')
    op.drop_index('uniq_active_block_guest', table_name='user_blocks', postgresql_where='active = true AND blocked_guest_id IS NOT NULL')
    op.drop_index('idx_user_blocks_list', table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index('idx_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_notification_user_unread', table_name='notifications')
    op.drop_index('idx_notification_user_list', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    op.drop_index('idx_lounge_name_lower', table_name='lounges')
    op.drop_index('idx_lounge_creator', table_name='lounges')
    op.drop_table('lounges')
    op.drop_table('local_credentials')
    op.drop_index('idx_auth_identity_user', table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('idx_temp_image_uploader', table_name='temp_images')
    op.drop_index('idx_temp_image_cleanup', table_name='temp_images')
    op.drop_table('temp_images')
    op.drop_index('idx_guest_actor_ttl', table_name='guest_actors')
    op.drop_table('guest_actors')
    op.drop_index('idx_email_verify_email', table_name='email_verification_sessions')
    op.drop_table('email_verification_sessions')
    # ### end Alembic commands ###
